create extension if not exists pgcrypto;

create type public.app_role as enum ('user', 'admin');
create type public.request_status as enum (
  'draft',
  'submitted',
  'under_review',
  'revision_required',
  'rejected',
  'approved',
  'completed'
);

create sequence if not exists public.request_number_seq start 1;

create or replace function public.generate_request_number()
returns text
language plpgsql
as $$
declare
  seq_num bigint;
begin
  seq_num := nextval('public.request_number_seq');
  return 'PTSP-' || to_char(now(), 'YYYY') || '-' || lpad(seq_num::text, 6, '0');
end;
$$;

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text unique,
  phone text,
  address text,
  role public.app_role not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_items (
  id bigint generated by default as identity primary key,
  service_id bigint not null references public.services(id) on delete cascade,
  name text not null,
  slug text not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_form_fields (
  id bigint generated by default as identity primary key,
  service_item_id bigint not null references public.service_items(id) on delete cascade,
  label text not null,
  name text not null,
  type text not null check (type in ('text', 'textarea', 'number', 'date', 'select')),
  placeholder text,
  is_required boolean not null default false,
  options text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_requirements (
  id bigint generated by default as identity primary key,
  service_item_id bigint not null references public.service_items(id) on delete cascade,
  document_name text not null,
  description text,
  is_required boolean not null default true,
  allowed_extensions text default 'pdf,jpg,jpeg,png',
  max_file_size_mb integer not null default 5,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete restrict,
  service_item_id bigint not null references public.service_items(id) on delete restrict,
  request_number text not null unique default public.generate_request_number(),
  status public.request_status not null default 'draft',
  submitted_at timestamptz,
  approved_at timestamptz,
  rejected_at timestamptz,
  completed_at timestamptz,
  revision_note text,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_request_answers (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.service_requests(id) on delete cascade,
  field_id bigint references public.service_form_fields(id) on delete set null,
  field_name text not null,
  field_value text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_request_documents (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.service_requests(id) on delete cascade,
  requirement_id bigint references public.service_requirements(id) on delete set null,
  file_name text not null,
  file_path text not null,
  file_type text,
  file_size bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (request_id, requirement_id)
);

create table if not exists public.service_request_reviews (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.service_requests(id) on delete cascade,
  reviewer_id uuid not null references public.profiles(id) on delete cascade,
  status public.request_status not null,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.generated_documents (
  id bigint generated by default as identity primary key,
  request_id uuid not null unique references public.service_requests(id) on delete cascade,
  file_name text not null,
  file_path text not null,
  generated_by uuid references public.profiles(id) on delete set null,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  request_id uuid references public.service_requests(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  notes text,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email, phone, address, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.email,
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(new.raw_user_meta_data ->> 'address', ''),
    'user'
  )
  on conflict (id) do update
  set email = excluded.email,
      full_name = excluded.full_name,
      phone = excluded.phone,
      address = excluded.address;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.services enable row level security;
alter table public.service_items enable row level security;
alter table public.service_form_fields enable row level security;
alter table public.service_requirements enable row level security;
alter table public.service_requests enable row level security;
alter table public.service_request_answers enable row level security;
alter table public.service_request_documents enable row level security;
alter table public.service_request_reviews enable row level security;
alter table public.generated_documents enable row level security;
alter table public.activity_logs enable row level security;

drop policy if exists "profiles own select" on public.profiles;
create policy "profiles own select"
on public.profiles
for select
using (auth.uid() = id or public.is_admin());

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update"
on public.profiles
for update
using (auth.uid() = id or public.is_admin());

drop policy if exists "admin insert profiles" on public.profiles;
create policy "admin insert profiles"
on public.profiles
for insert
with check (public.is_admin());

drop policy if exists "services public read" on public.services;
create policy "services public read"
on public.services
for select
using (is_active = true or public.is_admin());

drop policy if exists "services admin manage" on public.services;
create policy "services admin manage"
on public.services
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "items public read" on public.service_items;
create policy "items public read"
on public.service_items
for select
using (is_active = true or public.is_admin());

drop policy if exists "items admin manage" on public.service_items;
create policy "items admin manage"
on public.service_items
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "fields public read" on public.service_form_fields;
create policy "fields public read"
on public.service_form_fields
for select
using (true);

drop policy if exists "fields admin manage" on public.service_form_fields;
create policy "fields admin manage"
on public.service_form_fields
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "requirements public read" on public.service_requirements;
create policy "requirements public read"
on public.service_requirements
for select
using (true);

drop policy if exists "requirements admin manage" on public.service_requirements;
create policy "requirements admin manage"
on public.service_requirements
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "requests own select" on public.service_requests;
create policy "requests own select"
on public.service_requests
for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "requests own insert" on public.service_requests;
create policy "requests own insert"
on public.service_requests
for insert
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "requests own update" on public.service_requests;
create policy "requests own update"
on public.service_requests
for update
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "answers own access" on public.service_request_answers;
create policy "answers own access"
on public.service_request_answers
for all
using (
  exists (
    select 1
    from public.service_requests r
    where r.id = request_id
      and (r.user_id = auth.uid() or public.is_admin())
  )
)
with check (
  exists (
    select 1
    from public.service_requests r
    where r.id = request_id
      and (r.user_id = auth.uid() or public.is_admin())
  )
);

drop policy if exists "documents own access" on public.service_request_documents;
create policy "documents own access"
on public.service_request_documents
for all
using (
  exists (
    select 1
    from public.service_requests r
    where r.id = request_id
      and (r.user_id = auth.uid() or public.is_admin())
  )
)
with check (
  exists (
    select 1
    from public.service_requests r
    where r.id = request_id
      and (r.user_id = auth.uid() or public.is_admin())
  )
);

drop policy if exists "reviews own access" on public.service_request_reviews;
create policy "reviews own access"
on public.service_request_reviews
for select
using (
  exists (
    select 1
    from public.service_requests r
    where r.id = request_id
      and (r.user_id = auth.uid() or public.is_admin())
  )
);

drop policy if exists "reviews admin insert" on public.service_request_reviews;
create policy "reviews admin insert"
on public.service_request_reviews
for insert
with check (public.is_admin());

drop policy if exists "generated own access" on public.generated_documents;
create policy "generated own access"
on public.generated_documents
for all
using (
  exists (
    select 1
    from public.service_requests r
    where r.id = request_id
      and (r.user_id = auth.uid() or public.is_admin())
  )
)
with check (public.is_admin());

drop policy if exists "logs own access" on public.activity_logs;
create policy "logs own access"
on public.activity_logs
for select
using (
  exists (
    select 1
    from public.service_requests r
    where r.id = request_id
      and (r.user_id = auth.uid() or public.is_admin())
  )
);

drop policy if exists "logs insert own" on public.activity_logs;
create policy "logs insert own"
on public.activity_logs
for insert
with check (actor_id = auth.uid() or public.is_admin());

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute procedure public.handle_updated_at();

drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at
before update on public.services
for each row execute procedure public.handle_updated_at();

drop trigger if exists service_items_set_updated_at on public.service_items;
create trigger service_items_set_updated_at
before update on public.service_items
for each row execute procedure public.handle_updated_at();

drop trigger if exists service_form_fields_set_updated_at on public.service_form_fields;
create trigger service_form_fields_set_updated_at
before update on public.service_form_fields
for each row execute procedure public.handle_updated_at();

drop trigger if exists service_requirements_set_updated_at on public.service_requirements;
create trigger service_requirements_set_updated_at
before update on public.service_requirements
for each row execute procedure public.handle_updated_at();

drop trigger if exists service_requests_set_updated_at on public.service_requests;
create trigger service_requests_set_updated_at
before update on public.service_requests
for each row execute procedure public.handle_updated_at();

drop trigger if exists request_answers_set_updated_at on public.service_request_answers;
create trigger request_answers_set_updated_at
before update on public.service_request_answers
for each row execute procedure public.handle_updated_at();

drop trigger if exists request_documents_set_updated_at on public.service_request_documents;
create trigger request_documents_set_updated_at
before update on public.service_request_documents
for each row execute procedure public.handle_updated_at();

drop trigger if exists generated_documents_set_updated_at on public.generated_documents;
create trigger generated_documents_set_updated_at
before update on public.generated_documents
for each row execute procedure public.handle_updated_at();

insert into storage.buckets (id, name, public)
values
  ('request-documents', 'request-documents', false),
  ('generated-documents', 'generated-documents', false)
on conflict (id) do nothing;

drop policy if exists "storage request docs own access" on storage.objects;
create policy "storage request docs own access"
on storage.objects
for select
using (
  bucket_id = 'request-documents'
  and (
    public.is_admin()
    or owner = auth.uid()
  )
);

drop policy if exists "storage generated docs own access" on storage.objects;
create policy "storage generated docs own access"
on storage.objects
for select
using (
  bucket_id = 'generated-documents'
  and (
    public.is_admin()
    or owner = auth.uid()
  )
);

drop policy if exists "storage admin manage request docs" on storage.objects;
create policy "storage admin manage request docs"
on storage.objects
for all
using (bucket_id = 'request-documents' and public.is_admin())
with check (bucket_id = 'request-documents' and public.is_admin());

drop policy if exists "storage admin manage generated docs" on storage.objects;
create policy "storage admin manage generated docs"
on storage.objects
for all
using (bucket_id = 'generated-documents' and public.is_admin())
with check (bucket_id = 'generated-documents' and public.is_admin());
